/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AppPrerequisitesRouteImport } from './routes/_app.prerequisites'
import { Route as AppPartnershipsRouteImport } from './routes/_app.partnerships'
import { Route as AppKnowledgeBridgeRouteImport } from './routes/_app.knowledge-bridge'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPrerequisitesRoute = AppPrerequisitesRouteImport.update({
  id: '/prerequisites',
  path: '/prerequisites',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnershipsRoute = AppPartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeBridgeRoute = AppKnowledgeBridgeRouteImport.update({
  id: '/knowledge-bridge',
  path: '/knowledge-bridge',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/knowledge-bridge': typeof AppKnowledgeBridgeRoute
  '/partnerships': typeof AppPartnershipsRoute
  '/prerequisites': typeof AppPrerequisitesRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/knowledge-bridge': typeof AppKnowledgeBridgeRoute
  '/partnerships': typeof AppPartnershipsRoute
  '/prerequisites': typeof AppPrerequisitesRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/knowledge-bridge': typeof AppKnowledgeBridgeRoute
  '/_app/partnerships': typeof AppPartnershipsRoute
  '/_app/prerequisites': typeof AppPrerequisitesRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/knowledge-bridge'
    | '/partnerships'
    | '/prerequisites'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/knowledge-bridge'
    | '/partnerships'
    | '/prerequisites'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/knowledge-bridge'
    | '/_app/partnerships'
    | '/_app/prerequisites'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/prerequisites': {
      id: '/_app/prerequisites'
      path: '/prerequisites'
      fullPath: '/prerequisites'
      preLoaderRoute: typeof AppPrerequisitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partnerships': {
      id: '/_app/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof AppPartnershipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge-bridge': {
      id: '/_app/knowledge-bridge'
      path: '/knowledge-bridge'
      fullPath: '/knowledge-bridge'
      preLoaderRoute: typeof AppKnowledgeBridgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppKnowledgeBridgeRoute: typeof AppKnowledgeBridgeRoute
  AppPartnershipsRoute: typeof AppPartnershipsRoute
  AppPrerequisitesRoute: typeof AppPrerequisitesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppKnowledgeBridgeRoute: AppKnowledgeBridgeRoute,
  AppPartnershipsRoute: AppPartnershipsRoute,
  AppPrerequisitesRoute: AppPrerequisitesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
